### ISSUE TITLE
LinkedinShareButton not working

### ISSUE THREAD

**Issue by shandysulen** [nygardk/react-share#261] opened 2019-10-03 22:02 UTC
Sharing via `<LinkedinShareButton />` is not working.

```
<LinkedinShareButton url={shareLink}>
    <LinkedinIcon size={32} round={true} />
</LinkedinShareButton>
```
I imagine this is due to some update to LinkedIn's sharing API, so the `<LinkedinShareButton />` needs to be updated as a result.

**Comment by cretto** [comment] 2019-10-22 13:51
Up

**Comment by amyiee** [comment] 2019-12-03 06:11
Hey there, I'm wondering if you can re-visit this issue. it doesn't seem to work on my end

**Comment by WilliamChou06** [comment] 2019-12-17 20:21
Looks like this is happening because LinkedIn cannot retrieve any metadata from the link to be shared.

You can reproduce this by changing the LinkedIn share button to point to any URL that generates a rich link (or not).

**Comment by nygardk** [comment] 2020-01-04 12:21
Fixed in `v4.0.0`.

**Closed by nygardk** 2020-01-04 12:21 UTC
