### ISSUE TITLE
EmailShareButton is not working in chrome in desktop

### ISSUE THREAD

**Issue by dgr8akki** [nygardk/react-share#140] opened 2018-03-13 11:42 UTC
EmailShareButton is not working in chrome in desktop, but it is working in mobile. Also in Edge, it is asking for chrome.

**Comment by aautio** [comment] 2018-04-08 11:28
I've not been able to reproduce this problem. For me the EmailShareButton seems to be working ok.

@dgr8akki what email client are you using? What does your browser do if you click a plain html mailto-link like this?

```<a href="mailto:foo@bar.com">click me</a>```

**Comment by dgr8akki** [comment] 2018-04-08 15:58
I am testing my website in emulation mode in Chrome browser windows laptop.

**Comment by charlesverge** [comment] 2018-04-23 02:10
@dgr8akki This may be a bug in chrome emulation mode, for me when in chome emulation mode it works the first time but not the second. This sounds more like a bug in chrome.

For others who don't know what the emulation mode is in chrome your can enable it by

1. Open your website, using Google Chrome browser.
2. Press F12 to open Chrome DevTools.
3. Turn on device mode by pressing the Toggle device mode icon. When device mode is enabled, the icon turns blue and the viewport transforms into a device emulator:

You can also toggle device mode on/off using the keyboard shortcut:

Ctrl+Shift+M (or Cmd+Shift+M on Mac).

https://www.templatemonster.com/help/how-to-use-google-chrome-device-emulation-feature.html

**Comment by aautio** [comment] 2018-12-04 18:15
I'm closing the issue as it seems to be a bug in the development setup, but not in the `react-share` library itself.

**Closed by aautio** 2018-12-04 18:15 UTC
