### ISSUE TITLE
Add an icon for instagram

### ISSUE THREAD

**Issue by ReasonableDeveloper** [nygardk/react-share#185] opened 2018-09-30 14:09 UTC
Hey, thank you for this awesome library. I would love to see an `InstagramIcon`. I know from [this issue](https://github.com/nygardk/react-share/issues/146) that instagram does not have a share feature but it would be good to add the icon so developers can link to instagram pages.

**Comment by aautio** [comment] 2018-12-04 18:49
Closing as a duplicate of #146

**Closed by aautio** 2018-12-04 18:49 UTC
